pr: none

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - job: build
        displayName: Build

        pool:
          vmImage: ubuntu-16.04

        steps:
          - script: |
              dotnet --info
              docker version
              docker-compose version
            displayName: Init

          - script: |
              docker pull library/consul:1.5.3
              docker pull hashicorp/terraform:0.12.18

              docker-compose up -d build-consul
            displayName: Restore

          - script: |
              docker-compose build
            displayName: Build

          - script: |
              docker-compose down --rmi local
            displayName: Cleanup
