pr: none

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - job: build
        displayName: Build

        pool:
          vmImage: ubuntu-16.04

        steps:
          - script: |
              dotnet --info

              echo "##vso[task.setvariable variable=PATH;]$PATH:~/.dotnet/tools"
              dotnet tool install Cake.Tool --global --version 0.33.0
              dotnet tool install GitVersion.Tool --global --version 4.0.1-beta1-65

              dotnet tool list --global
            displayName: Init - .NET

          - script: |
              dotnet cake build.cake --target=Init --exclusive
            displayName: Init

          - script: |
              dotnet cake build.cake --target=Restore --exclusive
            displayName: Restore

          - script: |
              dotnet cake build.cake --target=Build --exclusive
            displayName: Build

          - script: |
              dotnet cake build.cake --target=Test --exclusive
            displayName: Test

          - script: |
              dotnet cake build.cake --target=Clean --exclusive
            displayName: Clean
            condition: always()

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - job: init
        displayName: Init

        pool:
          vmImage: ubuntu-16.04

        steps:
          - script: |
              dotnet --info

              echo "##vso[task.setvariable variable=PATH;]$PATH:~/.dotnet/tools"
              dotnet tool install Cake.Tool --global --version 0.33.0
              dotnet tool install GitVersion.Tool --global --version 4.0.1-beta1-65

              dotnet tool list --global
            displayName: Init - .NET

          - script: |
              dotnet cake build.cake --target=Init --exclusive
            displayName: Init

          - script: |
              docker pull hashicorp/terraform:0.12.18

              docker pull library/consul:1.5.3
              docker-compose up -d build-consul
            displayName: Restore

          - script: |
              docker-compose build sample-device-linux

              docker-compose build sample-device-windows
            displayName: Build

          - script: |
              docker-compose run sample-device-linux init

              docker-compose run sample-device-windows init
            displayName: Test

          - script: |
              dotnet cake build.cake --target=Clean --exclusive
            displayName: Clean
            condition: always()
