pr: none

variables:
  - group: pipeline

stages:
  - template: ./build/azp/sample.azure-pipelines.yml
    parameters:
      options:
        - sample: [ 'device', 'linux' ]
        - sample: [ 'device', 'windows' ]
