trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
pr: none

variables:
  - group: pipeline

stages:
  - template: ./build/azp/sample.azure-pipelines.yml
    parameters:
      samples:
        - name: [ 'device', 'linux' ]
        - name: [ 'device', 'windows' ]
