version: "3"

services:
  gitversion:
    build:
      context: ./build/docker/
      dockerfile: ./gitversion.Dockerfile
    volumes:
      - ./:/opt/gitversion/
    command: /showvariable SemVer

  registry:
    build:
      context: ./build/docker/
      dockerfile: ./registry.Dockerfile
    volumes:
      - ./artifacts/registry/data/:/var/lib/registry/
    ports:
      - "5000:5000"

  consul:
    build:
      context: ./build/docker/
      dockerfile: ./consul.Dockerfile
    volumes:
      - ./artifacts/consul/data/:/consul/data/
    ports:
      - "8500:8500"
    command: agent

  terraform:
    build:
      context: ./
      dockerfile: ./build/docker/terraform.Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
    volumes:
      - ./:/opt/terraform/
    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:
    entrypoint: /bin/sh

  sample:
    build:
      context: ./
      dockerfile: ./build/docker/sample.Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        SAMPLE_NAME: ${SAMPLE_NAME}
    image: ${SAMPLE_IMAGE}
    volumes:
      - ./samples/${SAMPLE_NAME}/.terraform/:/opt/terraform/samples/${SAMPLE_NAME}/.terraform/
    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:
    command: -help
