version: '3'

services:
  gitversion:
    build:
      context: ./build/docker/
      dockerfile: ./gitversion.Dockerfile

    volumes:
      - ./:/work/

  registry:
    build:
      context: ./build/docker/
      dockerfile: ./registry.Dockerfile

    volumes:
      - ./.registry/data/:/var/lib/registry/

    ports:
      - 5000:5000

  consul:
    build:
      context: ./build/docker/
      dockerfile: ./consul.Dockerfile

    volumes:
      - ./.consul/data/:/consul/data/

    ports:
      - 8500:8500

  sample:
    image: ${DOCKER_REGISTRY}gusztavvargadr/packet/sample-${SAMPLE_NAME}:${DOCKER_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./build/docker/sample.Dockerfile
      args:
        SAMPLE_NAME: ${SAMPLE_NAME}

    volumes:
      - ./samples/${SAMPLE_NAME}/.terraform/:/opt/gusztavvargadr/packet/samples/${SAMPLE_NAME}/.terraform/

    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:
