version: '3'

services:
  gitversion:
    build:
      context: ./build/docker/
      dockerfile: ./gitversion.Dockerfile

    volumes:
      - ${REPO_DIR}:/opt/gitversion/

    command: /showvariable SemVer

  registry:
    build:
      context: ./build/docker/
      dockerfile: ./registry.Dockerfile

    volumes:
      - ${REPO_DIR}artifacts/registry/data/:/var/lib/registry/

    ports:
      - '5000:5000'

  consul:
    build:
      context: ./build/docker/
      dockerfile: ./consul.Dockerfile

    volumes:
      - ${REPO_DIR}artifacts/consul/data/:/consul/data/

    ports:
      - '8500:8500'

  terraform:
    build:
      context: ./build/docker/
      dockerfile: ./terraform.Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}

    volumes:
      - ${REPO_DIR}:/opt/terraform/

    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:

  sample:
    build:
      context: ./
      dockerfile: ./build/docker/sample.Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        SAMPLE_NAME: ${SAMPLE_NAME}

    image: ${SAMPLE_REGISTRY}${SAMPLE_NAME}:${SAMPLE_TAG}

    volumes:
      - ${REPO_DIR}samples/${SAMPLE_NAME}/.terraform/:/opt/terraform/samples/${SAMPLE_NAME}/.terraform/

    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:
