version: '3'

services:
  sample-device-linux:
    image: ${DOCKER_REGISTRY}sample-device-linux:latest
    build:
      context: ./
      dockerfile: ./build/docker/sample.Dockerfile
      args:
        name: device-linux

    volumes:
      - ./samples/device-linux/.terraform/:/opt/gusztavvargadr/packet/samples/device-linux/.terraform/

    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:

  sample-device-windows:
    image: ${DOCKER_REGISTRY}sample-device-windows:latest
    build:
      context: ./
      dockerfile: ./build/docker/sample.Dockerfile
      args:
        name: device-windows

    volumes:
      - ./samples/device-windows/.terraform/:/opt/gusztavvargadr/packet/samples/device-windows/.terraform/

    environment:
      CONSUL_HTTP_ADDR:
      PACKET_AUTH_TOKEN:
