#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  vscode:
    build:
      context: ./
      dockerfile: ./vscode.Dockerfile

    volumes:
      - ../:/workspace/:cached
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      COMPOSE_PROJECT_NAME: packet_devcontainer
      DOCKER_REGISTRY: ${DOCKER_REGISTRY:-localhost:5000/gusztavvargadr/packet/}
      CONSUL_HTTP_ADDR: ${CONSUL_HTTP_ADDR:-consul:8500}
      PACKET_AUTH_TOKEN: ${PACKET_AUTH_TOKEN:-packet-auth-token}

    command: sleep infinity

  registry:
    build:
      context: ./
      dockerfile: ./registry.Dockerfile

    volumes:
      - ./.registry/data/:/var/lib/registry/

    ports:
      - "5000:5000"

  consul:
    build:
      context: ./
      dockerfile: ./consul.Dockerfile

    volumes:
      - ./.consul/data/:/consul/data/

    ports:
      - "8500:8500"
